---
- hosts: ffw-test ffw-dev-vb
  become: true

  tasks:
    # Update the machines before installing any software
    - name: Install Apa che.
      apt: name = {{ item }} state=present
      with_items:
        - httpd
        - httpd-devel

    - name: Copy configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: "httpd.conf"
          dest: "/etc/httpd/conf/httpd.conf"
        - src: "httpd-vhosts.conf"
          dest: "/etc/httpd/conf/httpd-vhosts.conf"
    - name: Make sure Apache is started now and at boot time.
      service: name=httpd state=started enabled=yes
      
